#!/usr/bin/env bash
set -e

if [[ ! -f serf ]]
then
  echo "Require local serf; exiting"
  exit 1
fi

rebar3 vir release

nix-build release.nix

if [[ -e _etwas ]]
then
  rm -rf _etwas
fi

mkdir -p _etwas

label=$(cat deployment/label)

cd _etwas

../etwas ../result rtsv2-release-$label

cp ../serf rtsv2-release-$label/bin

tar -cavf rtsv2-release-$label.tgz rtsv2-release-$label
