#!/usr/bin/env bash
set -e

find . -name "*.beam" -delete
rm -rf server/output
rm -rf server/compiled_ps
rebar3 compile
rebar3 vir "${@}" release

if [[ -e _etwas ]]
then
  rm -rf _etwas
fi

mkdir -p _etwas

nix-build release.nix -o _etwas/result

label=$(cat deployment/label)

cd _etwas

etwas result "rtsv2-release-$label"

tar -cavf "rtsv2-release-$label.tgz" "rtsv2-release-$label"
