export const enum ProtocolDefinedStatusCode {
  NormalClosure = 1000,
  GoingAway = 1001,
  ProtocolError = 1002,
  DataNotAcceptable = 1003,
  Reserved1 = 1004,
  Reserved2 = 1005,

  // This is a reserved code that a server MUST NOT send.
  // Browsers use this to flag that a connection closed without
  // a close frame.
  Client_ConnectionClosedAbnormally = 1006,

  DataInconsistentWithType = 1007,
  PolicyViolation = 1008,
  TooBig = 1009,

  // Generated by a client to indicate the server
  // didn't respond with a required extension
  Client_ExpectedExtension = 1010,

  UnexpectedCondition = 1011,

  // This is a reserved code that a server MUST NOT send.
  // Browsers use this to flag that a connection is closed
  // due to a TLS handshake failure.
  Client_TLSFailure = 1015
}

export const enum RTSDefinedStatusCode {
  StreamFinished = 4000,
}
