get:
  summary: /suport/timedRoutes/
  description: Returns the route a stream took to get from source to current location.
  tags:
    - Support Api
  responses:
    '200':
      description: OK
      content:
        application/json-ld:
          schema:
            type: array
            items:
              type: object
              properties:
                pop:
                  type:string
                servers:
                  type: array
                  items:
                    type: string

    '404':
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '../schemas/Problem.yaml'
